# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/

# Data
data_path: "/home/zeynepboztoprak/code/project01_solution/data/cell_data.h5"
train_brains:
  - B02
  - B05
  - B07
val_brains:
  - B20
test_brains:
  - B01
mean: 153.84
std: 49.132
tile_size: 128

# Optimization Parameters
lr: 0.001
weight_decay: 0.0001

# Model
latent_dim: 256

# Training
device: cuda  # Change to cpu/cuda depending on your hardware
batch_size: 64
num_workers: 12
train_epoch_size: 65_536
num_epochs: 50
log_interval: 100

# Validation
val_epoch_size: 512


